We're meeting up again because Wednesday's meeting did not last 2 hours (due to trying to find a room; our normal meeting room became unavaible from 12-4pm that day)

On Wedneday evening, Kelly reported that we do not need to write our own tests, and that using the tests that are already provided:
When we looked more into the scripting and since the logic of CommonPasswordValidator is in this link: https://github.com/nyu-ossd-s18/django/blob/master/django/contrib/auth/password_validation.py, it seems that we don't need to write any more tests. The actual test module that uses CommonPasswordValidator is called auth_tests and the file we care about is https://github.com/nyu-ossd-s18/django/blob/master/tests/auth_tests/test_validators.py. If we only wanted to test the CommonPasswordValidatorTest, we can run ./runtests.py auth_tests.test_validators.CommonPasswordValidatorTest from /tests. I ran this as well as the complete test suite with ./runtests.py and there seem to be no problems.

So Kelly & Jessica ran tests with our changed code and got different result. The tests were ran _*twice*_ on Rohit's computer and we got the same outputs as Jessica's results 

Kelly:
- OK (skipped=873, expected failures=4)

Jessica & Rohit:
- OK (skipped=946, expected failures=4)

